### PR TITLE
Change one sign of a numerical solution

### PR DESCRIPTION
**Pull request by Qinayan**
In 'F_SoilMoisture.py' file:

Previous one:
RHS = Ss*theta_np1m/poros*Psi_n/dt+(theta_n-theta_np1m)/dt+C_np1m*Psi_np1m/dt + (K_np1m_ph-K_np1m_mh)/dz

Current one:
RHS = Ss*theta_np1m/poros*Psi_n/dt+(theta_n-theta_np1m)/dt+C_np1m*Psi_np1m/dt - (K_np1m_ph-K_np1m_mh)/dz

### CODE REVIEW

**Review by levuvietphong — CHANGES_REQUESTED** [review]
This request should be merged to "DEVELOPMENT" branch, not the MASTER branch. Please submit another pull request.

**Comment by Qinayan** [comment]
how to do it?

On Tue, Feb 28, 2017 at 4:02 PM, Phong Le <notifications@github.com> wrote:

> *@levuvietphong* requested changes on this pull request.
>
> This request should be merged to "DEVELOPMENT" branch, not the MASTER
> branch. Please submit another pull request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_HydroComplexity_SoilMoisture_pull_5-23pullrequestreview-2D24352621&d=DwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=a9SB0y8JJesmZS-6qWbNpDFDdzch9oPucsPoQ17PeJQ&m=cPvs2hkF7hWkXDvhlLyfFczNAEVpJ4eIeCJZnZ5Vvs8&s=PpCuwYeVrXMNDgaCzB3OEaYb1kHoTl771PhBlrw9Zjc&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQoYDd1J09yFoP7F4Wt460dj0bRyGj-5Foks5rhJmGgaJpZM4MO51x&d=DwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=a9SB0y8JJesmZS-6qWbNpDFDdzch9oPucsPoQ17PeJQ&m=cPvs2hkF7hWkXDvhlLyfFczNAEVpJ4eIeCJZnZ5Vvs8&s=ycM12EBtUEy5UfO2Ccrxl90R05y9uPRYnsy6ZngdGvw&e=>
> .
>



-- 
Qina Yan
Hydrosystems Laboratory
Civil and Environmental Engineering
University of Illinois at Urbana-Champaign

**Comment by kunxw** [comment]
Select 'development' branch from dropdown when you make new pull request

**Comment by Qinayan** [comment]
Thanks! It has been resubmitted. Please check.

On Tue, Feb 28, 2017 at 8:25 PM, kunxw <notifications@github.com> wrote:

> Select 'development' branch from dropdown when you make new pull request
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_HydroComplexity_SoilMoisture_pull_5-23issuecomment-2D283225758&d=DwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=a9SB0y8JJesmZS-6qWbNpDFDdzch9oPucsPoQ17PeJQ&m=7qVYy2Ifuvjx1cBsz8LCfO-aiBimQVww1xI24thJctI&s=OWhTfWbZ4IZGk2J76SoNemcQiuVGNoAgGH4QC-BNFY4&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQoYDVH1YlHwW8RmSq4Rk47LHw1-2DM9fCks5rhNcugaJpZM4MO51x&d=DwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=a9SB0y8JJesmZS-6qWbNpDFDdzch9oPucsPoQ17PeJQ&m=7qVYy2Ifuvjx1cBsz8LCfO-aiBimQVww1xI24thJctI&s=GVlGA6szy0_0RMGw2yG-m6SNypI4f5bq0-RgZQ56DCQ&e=>
> .
>



-- 
Qina Yan
Hydrosystems Laboratory
Civil and Environmental Engineering
University of Illinois at Urbana-Champaign

**Comment by levuvietphong** [comment]
How to run a test for Qina's request? Just clone her repo to my computer?

**Comment by kunxw** [comment]
I think you can checkout the pull request locally...
I'm double checking right now

**Comment by levuvietphong** [comment]
Updated code works well. We can merge.

**Pull request merged**
